#!/bin/bash
# Sets the given desktop file as default for all the file types it can open.
set -e
if [[ $# -lt 1 ]]; then
    echo "Usage: associateall target [steal]"
    echo "    steal lets target steal associations from another application."
    echo "    the .desktop extension is optional on both arguments."
    exit 1
fi
desktop="$1"
mimesource="$2"
[[ -z "$mimesource" ]] && mimesource="$desktop"
[[ $desktop != *".desktop" ]] && desktop="$desktop.desktop"
[[ $mimesource != *".desktop" ]] && mimesource="$mimesource.desktop"
fulldesktop="$HOME/.local/share/applications/$mimesource"
[[ -f "$fulldesktop" ]] || fulldesktop="/usr/share/applications/$mimesource"
[[ -f "$fulldesktop" ]]
mimetypes=$(cat "$fulldesktop" | grep MimeType= | sed -r -e 's:MimeType=::' -e 's:inode/[^;]*;::' -e 's:;: :g')
[[ -n "$mimetypes" ]]
if [[ "$desktop" != "$mimesource" ]]; then
    echo "Giving $1 all of $2's associations."
    "$0" "$1" > /dev/null
else
    echo "Associating $1 with all types it can open."
fi
xdg-mime default "$desktop" $mimetypes
