#!/usr/bin/env -S sh -eu
# Backup to Marina's borg repository.

# Self-sudo.
if [ "$(id -u)" -gt 0 ]; then exec sudo -k "$0"; fi

here=$(dirname "$(realpath "$0")")
borg () { "$here/borg-wrap" "$@"; }
borg_create () { borg create --exclude-from "$here/../borg-excludes" "$@"; }

# Export necessary env vars.
export BORG_REPO="ssh://marina@marina/~/borg"
BORG_PASSPHRASE=${BORG_PASSPHRASE:-$(sudo -H -u tiz pass show borg)}
export BORG_PASSPHRASE

# Aura, Workbox, and Marina use BTRFS + subvolumes. Cerebro uses EXT4.
# The entire BTRFS partition is mounted at /mnt/btrfs, which means those
# subvolumes appear as they are on-disk, and not in the active filesystem.
# Thus, less exclusions are necessary.
if [ -d /mnt/btrfs ]; then  # Aura, Workbox, Marina.
    # Exclude home, ensure it's done last.
    # shellcheck disable=SC2012 # It works fine, shut up.
    subvols="os/$(cat /this-os)"
    
    if [ -e "/mnt/btrfs/xusr" ]; then subvols="$subvols xusr"; fi
    if [ -e "/mnt/btrfs/home" ]; then subvols="$subvols home"; fi

    # Backup step.
    for vol in $subvols; do
        volname=$(basename "$vol")
        borg_create "::{hostname}-$volname-{now:%y%m%d%H%M}" "/mnt/btrfs/$vol"
    done
else  # Cerebro.
    subvols="root xusr"
    borg_create -e "dev/" -e "sys/" -e "proc/" -e "run/" -e "home/" -e "xusr/" \
     "::{hostname}-root-{now:%y%m%d%H%M}" "/"
    borg_create "::{hostname}-xusr-{now:%y%m%d%H%M}" "/xusr"
fi

# Aura has a Windows partition.
if [ -d /mnt/windows ]; then
    subvols="$subvols windows"
    borg_create "::{hostname}-windows-{now:%y%m%d%H%M}" /mnt/windows || :
fi

# Prune step.
for vol in $subvols; do
    case "$vol" in
        windows)  daily=0; weekly=0; monthly=4 ;;
        home)     daily=4; weekly=2; monthly=2 ;;
        *)        daily=7; weekly=4; monthly=4 ;;
    esac
    borg prune --list --stats --prefix "{hostname}-$vol-" \
     --keep-daily "$daily" --keep-weekly "$weekly" --keep-monthly "$monthly"
done
