#!/bin/sh
# Set default options for borg.
set -eu
depends borg pass

if [ "$(id -u)" -gt 0 ]; then
	exec sudo --preserve-env=BORG_PASSPHRASE "$0" "$@"
fi

BORG_REPO=${BORG_REPO:-"ssh://marina@marina/~/borg"}
BORG_PASSPHRASE=${BORG_PASSPHRASE:-$(sudo -H -u tiz pass show borg)}
export BORG_REPO BORG_PASSPHRASE

cmd=${1}; shift
case "$cmd" in
create)
	# It sets paths in the archive relatively which is stupid.
	# Changing to the directory to be backed up fixes that.
	for arg; do
		shift
		if [ -d "$arg" ]; then cd "$arg"; set -- "$@" ./
		else set -- "$@" "$arg"; fi
	done
	# Add default options.
	set -- --list --stats --filter AME \
	 --compression zstd,16 --exclude-caches "$@"
	;;
esac

exec borg "$cmd" --verbose --progress --show-rc "$@"
