#!/bin/bash
# Whew, way simpler! :D
pkill conky
for dir1 in "$HOME/.conky" "${XDG_CONFIG_HOME:-$HOME/.config}/conky"; do
    if [[ -d "$dir1" ]]; then
        for dir2 in "$dir1/"*; do
            if [[ -f "$dir2/$HOSTNAME.rc" ]]; then
                cd "$dir2"; conky -d -c "$HOSTNAME.rc"
            fi
        done
    fi
done
