#!/bin/sh

target="$1"; UID=$(id -u)
if [ -z "$target" ]; then
    if [ -e "/run/user/$UID/conky/ontop" ];
        then target=below
        else target=above
    fi
fi

if [ "$target" = "below" ]; then
    state="below"
    remove="above"
    rm "/run/user/$UID/conky/ontop" || :
else
    state="above"
    remove="below"
    touch "/run/user/$UID/conky/ontop" || :
fi

for t in Todo-Conky QuodLibet-Conky QuodLibet-Conky-Cover; do
    wmctrl -F -r "$t" -b "remove,$remove"
    wmctrl -F -r "$t" -b "add,$state"
done
