#!/bin/sh

hide=0

target="${1:-}"; UID=$(id -u)
if [ -z "$target" ]; then
    if [ -e "/run/user/$UID/conky/ontop" ];
        then target=below
        else target=above
    fi
fi

for t in Todo-Conky Music-Conky; do
    if [ "$target" = "below" ]; then
        wmctrl -F -r "$t" -b remove,above
        wmctrl -F -r "$t" -b add,below
        if [ "$hide" = "1" ]; then xdotool search --name "$t" windowunmap; fi
        rm "/run/user/$UID/conky/ontop" || :
    else
        if [ "$hide" = "1" ]; then xdotool search --name "$t" windowmap; fi
        wmctrl -F -r "$t" -b remove,below
        wmctrl -F -r "$t" -b add,above
        touch "/run/user/$UID/conky/ontop" || :
    fi
done
