#!/bin/sh
# Disconnect all currently connected bluetooth controllers.
# Requires MGMonit to be in use.
set -eu

if ! [ -d "/run/moltengamepad/slots" ]; then
	die "MGMonit must be in use to disconnect connected bluetooth controllers."
fi

cd /run/moltengamepad/slots
for slot in *; do
	if [ -r "$slot/btaddr" ]; then
		bluetoothctl disconnect "$(cat "$slot/btaddr")" || : &
	fi
done
