#!/bin/sh
usage () { script=$(basename "$0"); cat <<EOF
$script -- Checks for script dependencies. If any are not present, prints
out their names with an error message and then exits 1, which will cause
scripts using set -e to exit, or can be paired with \`|| exit 1\`.
Sends a notification too, which is handy if you have it set up, switch
distros, and forget to install a dependency.
EOF
exit "${1:-0}"; }
case "${1:-}" in -h|--help|--usage|"") usage 0 ;; esac
set -eu

for arg; do
	if ! [ -x "$(command -v "${1:?}")" ]; then
		missing="${missing:+$missing }$arg"
	fi
done

if [ "${missing:-}" ]; then
	cat <<EOF
This script depends on the following missing utilities. Please install them.
    $missing
EOF
notify-send "Script failed" \
 "A script failed due to missing dependencies:\n    $missing"
exit 1
fi
