#!/bin/bash
# Change the color of DualShock 4 LEDS, and also setup udev rules and perms.
# This is a stark contrast to the xpad-leds script; games like Transistor and
# TowerFall make use of the light bar so it needs to be user writable.

# Usage: ds4-lightbar INDEX|all|newest (R G B)|default|off
#   Change per-controller defaults by editing this file.

ledpath="/sys/class/leds/0005:054C:05C4"

defaults=(
    "0 20 30"
    "30 0 20"
    "30 10 0"
    "10 30 0"
)

if [[ "$1" == "install" ]]; then
    # Install udev rule.
    [[ "$(whoami)" != "root" ]] && exec sudo "$0" "$@"
    cat > /etc/udev/rules.d/50-ds4-lightbar.rules <<EOF
SUBSYSTEM=="input", DRIVERS=="sony", RUN+="$(readlink -f "$0") setup"
EOF
    udevadm control --reload
    exit
elif [[ "$1" == "setup" ]]; then
    # Make leds user writable.
    [[ "$(whoami)" != "root" ]] && exec sudo "$0" "$@"
    for led in $ledpath.*; do
        chmod a+w $led/brightness;
    done
    # Set default light.
    "$0" newest default
elif [[ "$#" =~ 0|1|3 ]]; then
    echo "Usage: ds4-lightbar INDEX|all|newest (R G B)|default|off"
    echo "  Edit this script to set the default color."
    exit 1
else  # Convenient light-changing API.
    index=$1; r=$2; g=$3; b=$4  # Index refers to the nth available controller.
    
    # Find all available DS4 leds.
    leds=(); for led in $ledpath*\:global; do
        leds+=($(echo $led | cut -d: -f3 | cut -d. -f2))
    done
    
    # Define a function rather than repeating ourselves ad nauseum.
    set_led () {
        led=${leds[$1 - 1]}; [[ "$led" ]] || return
        if [[ "$2" == "off" ]]; then echo 0 > $ledpath.$led\:global/brightness
        elif [[ "$2" == "default" ]]; then
            # Bash functions have no sense of scope. We can peek at the index.
            default=${defaults[$1 - 1]}
            [[ "$default" ]] || {
                echo "No default color defined for controller $index."
                default=${defaults[0]}
            }
            set_led $1 $default
        else
            echo 1 > $ledpath.$led\:global/brightness
            echo $2 > $ledpath.$led\:red/brightness
            echo $3 > $ledpath.$led\:green/brightness
            echo $4 > $ledpath.$led\:blue/brightness
        fi
    }
    
    if [[ "$index" == "all" ]]; then
        for i in $(seq 1 ${#leds[@]}); do set_led $i $r $g $b; done;
    elif [[ "$index" == "newest" ]]; then set_led ${#leds[@]} $r $g $b
    else set_led $index $r $g $b; fi
fi
