#!/bin/sh
# Change the color of DualShock 4 LEDS, and also setup udev rules and perms.
# This is a stark contrast to the xpad-leds script; games like Transistor and
# TowerFall make use of the light bar so it needs to be user writable.
#
# Usage: ds4-lightbar INDEX|all (R G B)|default|default#|off
# Install requisite udev rules and config with ds4-lightbar install.
# Change per-controller defaults by editing /etc/ds4-lightbar.colors.
set -eu

rundir=/run/ds4-lightbar
sysdir=/sys/bus/hid/drivers/sony
colorlist=/etc/ds4-lightbar.colors


set_led () {
    target=${1:?}
    led="$rundir/$target";
    if ! [ -e "$led" ]; then return; fi
    nth=${2#default}
    if [ "$2" = "off" ]; then
        echo 0 > "$led"/global/brightness
    elif [ "$2" = "default" ] || { [ "$nth" != "$2" ] && \
     [ "$nth" -ge 0 ] 2>/dev/null; }; then
        colors=$(wc -l "$colorlist" | cut -f1 -d" ")
        if [ "$nth" != "$2" ] && [ "$nth" -ge 0 ] 2>/dev/null; then
            target="$nth"
        fi
        target=$(((target - 1) % colors))
        # shellcheck disable=SC2046
        set_led "$1" $(sed -n "$((target + 1)){p;q;}" < "$colorlist")
    else
        printf 1 > "$led/global/brightness"
        printf %s "${2:-}" > "$led/red/brightness"
        printf %s "${3:-}" > "$led/green/brightness"
        printf %s "${4:-}" > "$led/blue/brightness"
    fi
}

if [ "$1" = "install" ]; then
    # Install udev rule.
    if [ "$(id -u)" -gt 0 ]; then exec sudo -k "$0" "$@"; fi
    cat > /etc/udev/rules.d/50-ds4-lightbar.rules <<EOF
# Only DS4 lightbars have the "global" led.
ACTION=="add", SUBSYSTEM=="leds", DRIVERS=="sony", DEVPATH=="*:global", \
 TAG+="ds4leds", RUN+="$(readlink -f "$0") udev"
ACTION=="remove", TAG=="ds4leds", RUN+="$(readlink -f "$0") udev"
EOF
    cat > /etc/tmpfiles.d/ds4-lightbar.conf <<EOF
D $rundir 0755 root root
f $rundir/log 0666 root root
EOF
    mkdir -p "$rundir"
    touch "$rundir/log"
    chmod a+w "$rundir/log"
    if ! [ -r "$colorlist" ]; then cat > "$colorlist" <<EOF
0 0 50
50 0 0
0 50 0
50 50 0
0 50 50
50 0 50
60 30 0
50 50 50
EOF
    fi
    udevadm control --reload
    exit
fi

exec >> "$rundir/log" 2>&1
printf "== %s | args: %s ==\n" "$(date)" "$*"
set -x

if [ "$1" = "udev" ]; then
    if [ "$(id -u)" -gt 0 ]; then exit 1; fi
    dev=${DEVPATH##*/}; dev=${dev%:global}
    #dev=$(basename "$DEVPATH" | sed 's/:global//')
    case "$ACTION" in
    add)
        # Make leds user writeable.
        find "$sysdir/$dev/leds" -name "brightness" \
         -execdir chmod a+w '{}' \;
        #chmod a+w "$sysdir/$dev"/leds/*/brightness;
        mkdir -p "$rundir"
        mkdir "$rundir/$dev"
        ln -s "$(find "$sysdir/$dev/leds/" -name "*global")" \
         "$rundir/$dev/global"
        ln -s "$(find "$sysdir/$dev/leds/" -name "*red")" \
         "$rundir/$dev/red"
        ln -s "$(find "$sysdir/$dev/leds/" -name "*green")" \
         "$rundir/$dev/green"
        ln -s "$(find "$sysdir/$dev/leds/" -name "*blue")" \
         "$rundir/$dev/blue"
        # Find a free index.
        index=1
        while true; do
            if ! [ -d "$rundir/$index" ]; then
                ln -sfn "$rundir/$dev" "$rundir/$index"
                "$0" "$index" default
                break
            fi
            index=$((index + 1))
        done ;;
    remove)
        for dir in "$rundir"/*; do
            if [ "$dir" = "$rundir/log" ]; then continue
            elif ! [ -e "$dir/global" ]; then
                rm -r "$dir"
            fi
        done ;;
    esac
elif [ "$#" -le 1 ] || [ "$#" -eq 3 ]; then
    printf "Usage: ds4-lightbar INDEX|all (R G B)|default|off\n"
    printf "  Edit this script to set the default colors.\n"
    exit 1
else  # Convenient light-changing API.
    # Target refers to either controller n or the kernel name of the controller.
    target="${1:?}"; r="${2:?}"; g="${3:-}"; b="${4:-}"
    
    if [ "$target" = "all" ]; then
        for i in $(seq 1 "$(find $rundir | wc -l)"); do
            set_led "$i" "$r" "$g" "$b"
        done
    else set_led "$target" "$r" "$g" "$b"; fi
fi
