#!/bin/bash
int="eDP1"; ext="VGA1"
pgrep -f '[a]rcxinit' && DISPLAY=:5
if (xrandr | egrep "$ext connected [0-9]"); then
    xrandr --output $int --primary --output $ext --off 
else
    current_mode="$(xrandr -q | \
     sed -n 's/.*current[ ]\([0-9]*\) x \([0-9]*\),.*/\1x\2/p')"
    xrandr --output $int --primary --output $ext --preferred \
     --scale-from $current_mode --same-as $int
fi
