#!/bin/sh
# Executes separate socket for geany per workspace. Copy geany.desktop to
# $HOME/.local/share/applications and change its exec to this to get the most
# benefit; you'll be able to work on different text-related tasks on each
# workspace without disrupting either window!
exec flatpak run --file-forwarding org.geany.Geany \
    --socket-file="$HOME/xdg/cache/geany-$(xdotool get_desktop)" @@ "$@" @@
