#!/bin/sh
# shellcheck disable=SC2029
# Make Marina do all the heavy lifting for hue-cli work.
set -eu

if [ "$(hostname)" = "Marina" ]; then
	if [ "$1" = "adm" ]; then
		shift
		/usr/bin/hueadm "$@"
	else
		/usr/bin/hue "$@"
	fi
else ssh marina /home/tiz/xdg/sync/scripts/hue "$@"
fi
