#!/bin/bash
# Cycle the specified hue light through the rainbow at the specified speed.
# Requires HuePL. Put it somewhere in your PATH or replace the variable below.

huepl="$(which huepl)"
[[ -x "$huepl" ]] || huepl="$(dirname "$0")/huepl"
[[ -x "$huepl" ]] || { echo "Can't find HuePL."; exit 1; }
light=$1; [[ "$light" ]] || { echo "Light index required."; exit 1; }
speed=${2:-on}; speed=${speed/on/1024}
transition=${3:-0.4}

regex="hs ([0-9]+) ([0-9]+)"
[[ $("$huepl" lights | grep "light $light") =~ $regex ]]
start_hue=${BASH_REMATCH[1]:-0}; hue=$start_hue
start_sat=${BASH_REMATCH[2]:-255}; sat=$start_sat

finish () { "$huepl" hs $light $start_hue $start_sat; }
trap finish EXIT

while true; do
    ((hue = (hue + speed) % 65536))
    "$huepl" hs $light $hue $sat || exit 1
    sleep $transition
done
