#!/bin/bash
# Shift hue and saturation toward specified target with given step.
# Requires HuePL. Put it somewhere in your PATH or replace the variable below.

huepl="$(which huepl)"
[[ -x "$huepl" ]] || huepl="$(dirname "$0")/huepl"
[[ -x "$huepl" ]] || { echo "Can't find HuePL."; exit 1; }
light="$1"; [[ "$light" ]] || { echo "Light index required."; exit 1; }
to="$2"; [[ "$to" ]] || { echo "Destination hue required."; exit 1; }
step="${3:-16}"
transition="${4:-0.4}"

regex="hs ([0-9]+) ([0-9])+"
[[ $("$huepl" lights | grep "light $light ") =~ $regex ]]
hue="${BASH_REMATCH[1]:-0}"
sat="${BASH_REMATCH[1]:-1}"
[[ $hue -eq $to ]] && exit
[[ $hue -gt $to ]] && step="-$step"

while [[ $hue -ne $to ]]; do
    ((hue += step))
    [[ $step -lt 0 ]] && [[ $hue -lt $to ]] && hue=$to;
    [[ $step -gt 0 ]] && [[ $hue -gt $to ]] && hue=$to;
    "$huepl" hs "$light" "$hue" "$sat" || exit 1
    sleep $transition
done
