#!/bin/bash
# Quickly raise or lower the brightness of the specified light to the target.
# Requires HuePL. Put it somewhere in your PATH or replace the variable below.

huepl="$(which huepl)"
[[ -x "$huepl" ]] || huepl="$(dirname "$0")/huepl"
[[ -x "$huepl" ]] || { echo "Can't find HuePL."; exit 1; }
light="$1"; [[ "$light" ]] || { echo "Light index required."; exit 1; }
to="${2/on/}"
step="${3:-16}"
transition="${4:-0.4}"

regex="bri ([0-9]+)"
[[ $("$huepl" lights | grep "light $light") =~ $regex ]]
bri="${BASH_REMATCH[1]:-0}"
[[ "$to" ]] || { [[ $bri -gt 127 ]] && to=1 || to=254 ; }
[[ $bri -eq $to ]] && exit
[[ $bri -gt $to ]] && step="-$step"

while [[ $bri -ne $to ]]; do
    ((bri += step))
    [[ $step -lt 0 ]] && [[ $bri -lt $to ]] && bri=$to;
    [[ $step -gt 0 ]] && [[ $bri -gt $to ]] && bri=$to;
    "$huepl" bri "$light" "$bri" || exit 1
    sleep $transition
done
