#!/bin/bash
# Slowly raise or lower the brightness of the specified light to the target.
# Requires HuePL. Put it somewhere in your PATH or replace the variable below.

huepl="$(which huepl)"
[[ -x "$huepl" ]] || exit 1
light="$1"; [[ "$light" ]] || { echo "Light index required."; exit 1; }
to="$2"
delay="${3:-0.4}"

regex="bri ([0-9]+)"
[[ $("$huepl" lights | grep "light $light") =~ $regex ]]
bri="${BASH_REMATCH[1]:-0}"
[[ "$to" ]] || { [[ $bri -gt 127 ]] && to=0 || to=254 ; }
[[ $bri -eq $to ]] && exit
[[ $bri -lt $to ]] && step=1 || step=-1

while [[ $bri -ne $to ]]; do
    ((bri += step))
    "$huepl" bri "$light" "$bri" || exit 1
    sleep $delay
done
