#!/bin/bash
# Cycle the specified hue light through the rainbow at the specified speed.
# Requires HuePL. Put it somewhere in your PATH or replace the variable below.

huepl="$(which huepl)"
[[ -x "$huepl" ]] || exit 1
light="$1"; [[ "$light" ]] || { echo "Light index required."; exit 1; }
speed="${2:-1024}"
transition="${3:-0.4}"

regex="hs ([0-9]+) ([0-9]+)"
[[ $("$huepl" lights | grep "light $light") =~ $regex ]]
hue="${BASH_REMATCH[1]:-0}"
sat="${BASH_REMATCH[2]:-255}"

while true; do
    ((hue = (hue + speed) % 65536))
    "$huepl" hs "$light" "$hue" "$sat" || exit 1
    sleep $transition
done
