#!/bin/sh
# Preset laptop light settings.
switch=$1
[ -z "$switch" ] && switch=$(cat /sys/class/power_supply/ADP1/online)
[ -z "$switch" ] && exit
if [ "$switch" -eq 1 ]; then
    /home/common/bin/lcd-brightness set 75
    #/home/common/bin/kbd-brightness 3
else
    /home/common/bin/lcd-brightness set 20
    #/home/common/bin/kbd-brightness 1
fi
