#!/bin/sh
# Automated lcd brightness changer.
[ "$(id -un)" != "root" ] && exec sudo "$0" "$@"

dev=/sys/class/backlight/acpi_video0
step_base=$(($(cat "$dev/max_brightness") / 100))
step="$2"
[ -z "$step" ] && exit
step=$((step_base * step))

timer=0; while ! [ -e "$dev" ] && [ "$timer" -lt 30 ]; do
    sleep 1; timer=$((timer + 1)); done
if ! [ -e "$dev" ]; then exit; fi

case $1 in
    +)  echo $(($(cat "$dev/brightness") + step)) > "$dev/brightness" ;;
    -)  echo $(($(cat "$dev/brightness") - step)) > "$dev/brightness" ;;
    *)  echo "$step" > "$dev/brightness" ;;
esac
