#!/bin/sh
# Swap 1st and 2nd player slots for games where player order matters.
set -eu

slotdir=/run/moltengamepad/slots

message () {
    printf "%s; %s\n" "$1" "$2"
    if [ -x "$(command -v sys-notify)" ]; then
        sys-notify "$1" "$2"
    else notify-send "$1" "$2"; fi
}

if ! [ -e "$slotdir" ]; then
    message "Can't swap" "MG monitor isn't running."
    exit 1
elif ! [ -e "$slotdir/1" ]; then
    message "Can't swap" "No controllers connected."
    exit 1
elif ! [ -e "$slotdir/2" ]; then
    message "Can't swap" "There is no second player."
    exit 1
fi

first=$(cat "$slotdir/1/mgdev")
second=$(cat "$slotdir/2/mgdev")

mgexec "move $first to virtpad2"
mgexec "move $second to virtpad1"
