#!/bin/sh
# Outputs information about current song for use by both conky and OBS.
# Requires imagemagick. Configure Quod Libet's Picture Saver plugin to save
# the cover to $HOME/.cache/ql.current.cover
set -eu

[ -x "$(command -v convert)" ]
[ -x "$(command -v playerctl)" ]

players_base="spotify,quodlibet"
rundir="/run/user/$(id -u)/song-info"
nocover="$HOME/xdg/sync/conky/QLInfo/nocover.png"
artdir="$HOME/mus/art"
qlpath="$HOME/.quodlibet"
size="128"
opts="${XDG_CONFIG_HOME:-$HOME/.config}/script-options"
# shellcheck disable=SC1090
if [ -r "$opts" ]; then . "$opts"; fi

format='{{status}}
{{mpris:trackid}}
{{mpris:artUrl}}
{{title}}
{{artist}}
{{albumArtist}}
{{album}}'

pctl () { playerctl -p "$players" "$@"; }

puts () { printf %s\\n "$*"; }

spotpris_update () {
	players=${players_base}
	spotpris=$(playerctl -l | grep spotpris | head -n1)
	if [ "$spotpris" ]; then players="$spotpris,$players"; fi
}

filter () { sed -E -f "${HOME}/xdg/sync/music-watch.sed"; }

filter_filename () {
	sed -E -e 's|[\\\*\?;"\<\>\|]||g' -e 's|[ \.]+$||g' \
	 -e 's|: | - |g' -e 's|[:~]|-|g' -e 's|/|+|g'  # TODO
}

clear_info () {
	printf \\n > "title.txt"
	printf \\n > "artist.txt"
	printf \\n > "album.txt"
	printf \\n > "artistalbum.txt"
	convert -size "16x16" xc:transparent png32:cover.png
	cp cover.png label.png
}

make_cover () {    
	convert cover-start \
	 -resize "${size}x${size}^" -gravity center -extent "${size}x${size}" \
	 1-resized.png
	
	convert 1-resized.png \
	 \( +clone  -alpha extract \
		-draw 'fill black polygon 0,0 0,12 12,0 fill white circle 12,12 12,0' \
		\( +clone -flip \) -compose Multiply -composite \
		\( +clone -flop \) -compose Multiply -composite \
	 \) -alpha off -compose CopyOpacity -composite 2-rounded-corners.png
	
	convert 2-rounded-corners.png \
	 -alpha off -fill white -colorize 100% \
	 -draw 'fill black polygon 0,0 0,15 15,0 fill white circle 15,15 15,0' \
	 \( +clone -flip \) -compose Multiply -composite \
	 \( +clone -flop \) -compose Multiply -composite \
	 -background Gray50 -alpha Shape 3-thumbnail-mask.png
	
	convert 3-thumbnail-mask.png \
	 -bordercolor None -border 1x1 \
	 -alpha Extract -blur 0x10  -shade 130x30 -alpha On \
	 -background gray50 -alpha background -auto-level \
	 -function polynomial  3.5,-5.05,2.05,0.3 \
	 \( +clone -alpha extract  -blur 0x2 \) \
	 -channel RGB -compose multiply -composite \
	 +channel +compose -chop 1x1 \
	 4-thumbnail-lighting.png
	
	convert 1-resized.png \
	 -alpha Set 4-thumbnail-lighting.png \
	 \( -clone 0,1 -alpha Opaque -compose Hardlight -composite \) \
	 -delete 0 -compose In -composite \
	 5-glass-bubble.png
	
	convert 5-glass-bubble.png \
	 \( +clone -background black -shadow 90x4+0+0 \) +swap \
	 -background none -layers merge +repage \
	 cover-done.png
	
	mv cover-done.png cover.png
}

mkdir -p "$rundir"; cd "$rundir"
clear_info
spotpris_update
prev_status=""

pctl -f "$format" -F metadata 2> /dev/null | while read -r status; do
	if [ "$status" ]; then
		# We don't actually use the track ID, but we do query it to ensure
		# that the track is actually changing.
		# shellcheck disable=SC2034
		read -r trackid
		read -r arturl
		read -r title
		read -r artist
		read -r album_artist
		read -r album
	fi
	if [ "$status" != "Playing" ]; then clear_info
	else
		title=$(puts "$title" | filter)
		if ! [ "${title## }" ]; then clear_info; continue; fi
		artist=$(puts "$artist" | sed ':a;N;$!ba;s/\n/, /g' | filter)
		album=$(puts "$album" | filter)
		if ! [ "$album" ]; then
			album=$(sed -nr 's/^website=(.+)$/\1/p' "$qlpath/current")
		fi
		if ! [ "$album" ]; then album=${title}; fi
		artist_filter=$(puts "$album_artist" | filter_filename)
		album_filter=$(puts "$album" | filter_filename)
		artcache="$artdir/$artist_filter - $album_filter"
		puts "$title" > "title.txt"
		puts "$artist" > "artist.txt"
		puts "$album" > "album.txt"
		puts "$artist - $album" > "artistalbum.txt"
		arturl=$(puts "$arturl" | sed -E 's|open\.spotify\.com|i\.scdn\.co|')
		if [ -r "$artcache" ]; then
			cp "$artcache" cover-start
		else
			if ! curl -sL -o "$artcache" "$arturl"; then
				cover="$HOME/.cache/ql.current.cover"
				if ! [ -r "$cover" ]; then cover="$nocover"; fi
				cp "$cover" cover-start
			else
				cp "$artcache" cover-start
			fi
		fi
		make_cover || :
		make_label || :
		# If status went from playing to playing, a track change happened.
		if [ "$prev_status" = "Playing" ] && [ "$status" = "Playing" ]; then
			case "$(obsctl GetCurrentScene || :)" in
			"SoulCalibur VI") : ;;
			"Song Info"*) : ;;
			*)
				system-notify -i "$rundir/cover-start" \
				 "$title" "$artist\n$album" ;;
			esac
		fi
	fi
	prev_status="$status"
	if [ "${spoofy_genmon_id:-}" ]; then
		xfce4-panel --plugin-event="genmon-$spoofy_genmon_id":refresh:bool:true
	fi
done
