#!/bin/sh
export HOME=/home/tiz
export DISPLAY=:0.0
ql=$(command -v quodlibet)
[ -x "$ql" ] || ql=/xusr/bin/quodlibet
[ -x "$ql" ] || ql="ql_flatpak"
ql_flatpak () { flatpak run io.github.quodlibet.QuodLibet "$@"; }
task="$1"
shift
case "$task" in
    printweb)
"$ql" --print-playing '<title>\<br/\>
<artist>\<br/\>
<album>'
;;
    toggle)   "$ql" --play-pause    ;;
    play)     "$ql" --play          ;;
    pause)    "$ql" --pause         ;;
    back)     "$ql" --previous      ;;
    fwd)      "$ql" --next          ;;
    stop)     "$ql" --stop          ;;
    enqueue)  "$ql" --enqueue "$*"  ;;
    *)
"$ql" --print-playing '<title>
<artist>
<album>'
;;
esac
