#!/bin/bash
export HOME=/home/tiz
export DISPLAY=:0.0
ql=$(which quodlibet)
task="$1"
shift
case "$task" in
    printweb)
$ql --print-playing '<title>\<br/\>
<artist>\<br/\>
<album>'
;;
    toggle)   $ql --play-pause    ;;
    play)     $ql --play          ;;
    pause)    $ql --pause         ;;
    back)     $ql --previous      ;;
    fwd)      $ql --next          ;;
    stop)     $ql --stop          ;;
    enqueue)  $ql --enqueue "$@"  ;;
    print) ;&
    *)
$ql --print-playing '<title>
<artist>
<album>'
;;
esac
