#!/usr/bin/env -S sh -eu
# slick-menu -- Use rofi to create a menu for scripting.
#     Usage: slick-menu <prompt> <id> <option text> [id] [option text] ...
# If mgctl is present, will load the kbctl profile for gamepad menu control.
# Alternate option IDs and option texts. Prints the ID of the selected text to
# stdout. If canceled, prints nothing to stdout.

if ! [ -x "$(command -v rofi)" ]; then
	printf "This script requires rofi. Please install it.\n" >&2
	exit 1
fi

# Print the comment header of this file when asked for help.
usage () { sed -nE '/^#/!q; /SC[0-9]{4}/d; s/^#( |$)//p' "$0"; exit "${1:-0}"; }
case "${1:-}" in -h|--help|--usage|help|usage|"") usage 0 ;; esac

width="25%"
case "${1:-}" in -w|--width) width="$2"; shift 2 ;; esac

switch=0; count=0
prompt="$1"; shift

for arg; do
	# Allows providing blank args to skip an item.
	if ! [ "$arg" ]; then continue; fi
	if [ "$switch" -eq 0 ]; then
		ids="${ids:+$ids\n}$arg"
		switch=1
		count=$((count + 1))
	else
		texts="${texts:+$texts\n}$arg"
		switch=0
	fi
done

if [ "$switch" -eq 1 ]; then
	printf "Mismatched number of IDs and texts.\n" >&2
	exit 1
fi

if [ "$count" -eq 0 ]; then usage 1; fi

tmp=$(mktemp); trap 'rm -f $tmp' EXIT
sed 's/${WIDTH}/'"$width"'/' \
 "${XDG_CONFIG_HOME:-$HOME/.config}/rofi/slick-menu.rasi.in" > "$tmp"

if [ -x "$(command -v mgctl)" ]; then
	mgctl profiles temp kbctl
fi

result=$(printf %b\\n "$texts" | rofi -dmenu -p "$prompt" -no-custom -format d \
 -theme "$tmp" -theme-str "listview {lines: $count;}" || :)

printf %b\\n "$ids" | sed -n "$result p" || :

if [ -x "$(command -v mgctl)" ]; then
	sleep 0.5; mgctl profiles game
fi
