#!/bin/sh
# syslog-run -- Send a command's output to syslog and run it in the background.
#     Usage: syslog-run [-t|--tag tag] command [args]
# If the tag is not specified, the command's basename is used. If the basename
# is flatpak or a desktop launcher, it will set the tag from their args.
set -eu

# Print the comment header of this file when asked for help.
usage () { sed -nE '/^#/!q; /SC[0-9]{4}/d; s/^#( |$)//p' "$0"; exit "${1:-}"; }

case "${1:-}" in
	-h|--help|--usage|help|usage|"") usage 0 ;;
	-t|--tag) tag="$2"; shift 2 ;;
esac

# Find the Flatpak app name and use it as the tag.
if ! [ "${tag:-}" ]; then case "$(basename "$1")" in
flatpak)
	for arg; do
		if [ "$(basename "$arg")" = "flatpak" ] || [ "$arg" = "run" ]
			then continue
		elif printf %s\\n "$arg" | grep -Eq '\w+\.\w+\.\w+'; then
			tag="$arg"
			break
		fi
	done
	;;
*launch)
	if [ "${2:-}" ]; then tag="${2%.desktop}"; else exit 1; fi
	;;
esac; fi

"$@" 2>&1 | logger -t "${tag:-$(basename "$1")}" &
