#!/bin/sh
usage () { script=$(basename "$0"); cat <<EOF
$script -- Send a command's output to syslog and run it in the background.
If the tag is not specified, the command's basename is used. If the basename
is flatpak or a desktop launcher, it will set the tag from their args.

Usage:
    syslog-run [-t|--tag tag] command [args]
EOF
exit "${1:-0}"; }
set -eu

case "${1:-}" in
	-t|--tag) tag="$2"; shift 2 ;;
	-h|--help|--usage|"") usage 0 ;;
esac

# Find the Flatpak app name and use it as the tag.
if ! [ "${tag:-}" ]; then case "$(basename "$1")" in
flatpak)
	for arg; do
		if [ "$(basename "$arg")" = "flatpak" ] || [ "$arg" = "run" ]
			then continue
		elif printf %s\\n "$arg" | grep -Eq '\w+\.\w+\.\w+'; then
			tag="$arg"
			break
		fi
	done
	;;
*launch)
	if [ "${2:-}" ]; then tag="${2%.desktop}"; else exit 1; fi
	;;
esac; fi

"$@" 2>&1 | logger -t "${tag:-$(basename "$1")}" &
