#!/bin/sh
# hOI!!! im termmie put dis in yur bashrc!
# get many... DETERMINALATION!!! yayA!!!

if [ "${TERM##xterm}" != "$TERM" ] && [ "$DISPLAY" ] && \
 ! [ "$SSH_CLIENT$SSH_TTY" ]; then
    termmies="
hOI!!! im termmie!!!
an dis is my friend... termmie!!!
don forget my friend!
Hi. I'm Bob.
(Feeling of being watched.)
awawawawah!! linux... such a... CUTE!!!
term... WATCH EG!!!
eg... wil HATCH!!!
term... PROUD PARENT!!
term also allergic to windooz! hOIVS!
You have way too many temmienals.
    "
    wins=$(wmctrl -l)
    printf %s "$termmies" | while read -r tem; do
        if ! [ "$tem" ]; then continue; fi
        if ! printf %s "$wins" | grep -q "$tem"; then
            printf "\033]0;%s\007" "$tem"
            break
        fi
    done
fi

printf "* You are filled with determinalation.\n"
