#!/bin/sh
# Presents a GUI for cutting videos.
set -eu

puts () { printf %s\\n "$*"; }

_yad () {
    yad --class vid-cutter --name vid-cutter \
     --title "Vid-Cutter" --window-icon avidemux "$@"
}

increment () {
    offset="$2"
    secs=$(puts "$1" | awk -F: '{print $(NF)}')
    deci=$(puts "$secs" | cut -d. -f2)
    if [ "$deci" = "$secs" ]; then deci=000; fi
    secs=$(puts "$secs" | cut -d. -f1)
    secs=${secs#${secs%%[!0]*}}  # Strip leading zeroes.
    mins=$(puts "$1" | awk -F: '{print $(NF-1)}')
    if [ "$mins" = "$1" ]; then mins=0; fi    
    mins=${mins#${mins%%[!0]*}}
    hours=$(puts "$1" | awk -F: '{print $(NF-2)}')
    if [ "$hours" = "$1" ]; then hours=0; fi
    hours=${hours#${hours%%[!0]*}}
    puts "$((hours * 3600 + mins * 60 + secs + offset)).$deci"
}

[ -r "$1" ]
input="$1"

if [ -r "./.vid-cutter" ]; then . "./.vid-cutter"; fi

result=$(_yad --form --align left \
 --field "Directory:DIR" "${dir:-$(pwd)}" \
 --field "Clip name" "" \
 --field "Audio track" "" \
 --field "Thumbnail time" "" \
 --field "Start time" "" \
 --field "End time" "")

#group=$(puts "$result" | cut -d'|' -f1)
dir=$(puts "$result" | cut -d'|' -f1)
name=$(puts "$result" | cut -d'|' -f2)
audio=$(puts "$result" | cut -d'|' -f3)
thumb=$(puts "$result" | cut -d'|' -f4)
start=$(puts "$result" | cut -d'|' -f5)
end=$(puts "$result" | cut -d'|' -f6)

if [ ! "$thumb" ]; then thumb="$start"; fi

start=$(increment "$start" "${start_offset:-0}")
thumb=$(increment "$thumb" "${thumb_offset:-${start_offset:-0}}")
end=$(increment "$end" "${end_offset:-0}")

filename=$(puts "$name" | sed 's/[\\/:\*\?"<>\|\x01-\x1F\x7F]//g')

mkdir -p "$dir"

{
    puts "dir=\"$dir\""
    if [ "${start_offset:-}" ]; then puts "start_offset=$start_offset"; fi
    if [ "${thumb_offset:-}" ]; then puts "thumb_offset=$thumb_offset"; fi
    if [ "${end_offset:-}" ]; then puts "end_offset=$end_offset"; fi
} > .vid-cutter

if [ "$audio" = "all" ] || [ ! "$audio" ]; then audio="0:a?"
else audio="0:a:$audio"; fi

{ ffmpeg -ss "$thumb" -i "$input" -vframes 1 -s 1280x720 \
 -y "$dir/$filename.thumb.png" > /dev/null
 ffmpeg -ss "$start" -to "$end" -i "$input" -map 0:v -map "$audio" \
 -c copy -movflags faststart -avoid_negative_ts 1 \
 -y "$dir/$filename.mp4"
} | _yad --progress --auto-kill --auto-close --pulsate --hide-text
