#!/bin/bash
# Wait for specified process to exist, then optionally run a command.

# If anything blows up, jump ship.
set -e

# And now we wait.
proc="$1"
echo $proc
shift
test="$((ps aux | grep "$proc" | grep -v grep | grep -v waitproc) || true)"
timer=0
while [[ -z "$test" ]] && [[ $timer -lt 30 ]]; do
    sleep 1
    timer="$((timer + 1))"
    test="$((ps aux | grep "$proc" | grep -v grep | grep -v waitproc) || true)"
done

# Die if the process takes longer than 30 seconds to exist.
if [[ $timer -ge 30 ]]; then
    echo "Wait timed out." >&2
    exit 1
fi

# Run the command if one was given.
[[ $# -gt 0 ]] && exec "$@"
