#!/bin/bash
# Fixes LEDs for xpad driver.
[[ "$(whoami)" != "root" ]] && exec sudo "$0" "$@"

if [[ "$1" == "install" ]]; then
    cat > /etc/udev/rules.d/50-xpad-leds.rules <<EOF
SUBSYSTEM=="input", DRIVERS=="xpad", RUN+="$(readlink -f "$0")"
EOF
    cat > /etc/sudoers.d/xpad-leds.rules <<EOF
ALL ALL=(ALL) NOPASSWD: $(readlink -f "$0")
EOF
    udevadm control --reload
    exit
fi

index=0
for led in /sys/class/leds/xpad*; do
    #light=$((${led//[!0-9]/} % 4 + 6))
    light=$((index++ % 4 + 6))
    [[ "$1" == "off" ]] && light=0;
    echo $light > $led/brightness
done
